#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tempofme.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NineDragons_Account")]
	public partial class DataAccountContentDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTbl_giftcode(Tbl_giftcode instance);
    partial void UpdateTbl_giftcode(Tbl_giftcode instance);
    partial void DeleteTbl_giftcode(Tbl_giftcode instance);
    partial void InsertTbl_Member_Password(Tbl_Member_Password instance);
    partial void UpdateTbl_Member_Password(Tbl_Member_Password instance);
    partial void DeleteTbl_Member_Password(Tbl_Member_Password instance);
    partial void Insert_9d_event(_9d_event instance);
    partial void Update_9d_event(_9d_event instance);
    partial void Delete_9d_event(_9d_event instance);
    partial void Insert_9d_user(_9d_user instance);
    partial void Update_9d_user(_9d_user instance);
    partial void Delete_9d_user(_9d_user instance);
    partial void InsertUser_History(User_History instance);
    partial void UpdateUser_History(User_History instance);
    partial void DeleteUser_History(User_History instance);
    partial void Insert_9d_KTCItem(_9d_KTCItem instance);
    partial void Update_9d_KTCItem(_9d_KTCItem instance);
    partial void Delete_9d_KTCItem(_9d_KTCItem instance);
    partial void Insert_9d_new(_9d_new instance);
    partial void Update_9d_new(_9d_new instance);
    partial void Delete_9d_new(_9d_new instance);
    partial void Insert_9d_ad(_9d_ad instance);
    partial void Update_9d_ad(_9d_ad instance);
    partial void Delete_9d_ad(_9d_ad instance);
    partial void Insert_9d_percen(_9d_percen instance);
    partial void Update_9d_percen(_9d_percen instance);
    partial void Delete_9d_percen(_9d_percen instance);
    #endregion
		
		public DataAccountContentDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NineDragons_AccountConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataAccountContentDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAccountContentDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAccountContentDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAccountContentDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_giftcode> Tbl_giftcodes
		{
			get
			{
				return this.GetTable<Tbl_giftcode>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Member_Password> Tbl_Member_Passwords
		{
			get
			{
				return this.GetTable<Tbl_Member_Password>();
			}
		}
		
		public System.Data.Linq.Table<_9d_event> _9d_events
		{
			get
			{
				return this.GetTable<_9d_event>();
			}
		}
		
		public System.Data.Linq.Table<_9d_user> _9d_users
		{
			get
			{
				return this.GetTable<_9d_user>();
			}
		}
		
		public System.Data.Linq.Table<User_History> User_Histories
		{
			get
			{
				return this.GetTable<User_History>();
			}
		}
		
		public System.Data.Linq.Table<_9d_KTCItem> _9d_KTCItems
		{
			get
			{
				return this.GetTable<_9d_KTCItem>();
			}
		}
		
		public System.Data.Linq.Table<_9d_new> _9d_news
		{
			get
			{
				return this.GetTable<_9d_new>();
			}
		}
		
		public System.Data.Linq.Table<_9d_ad> _9d_ads
		{
			get
			{
				return this.GetTable<_9d_ad>();
			}
		}
		
		public System.Data.Linq.Table<_9d_percen> _9d_percens
		{
			get
			{
				return this.GetTable<_9d_percen>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_giftcode")]
	public partial class Tbl_giftcode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _item_id;
		
		private string _gift_code;
		
		private string _item_code;
		
		private string _group_user;
		
		private System.Nullable<int> _active_id;
		
		private string _active_user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onitem_idChanging(int value);
    partial void Onitem_idChanged();
    partial void Ongift_codeChanging(string value);
    partial void Ongift_codeChanged();
    partial void Onitem_codeChanging(string value);
    partial void Onitem_codeChanged();
    partial void Ongroup_userChanging(string value);
    partial void Ongroup_userChanged();
    partial void Onactive_idChanging(System.Nullable<int> value);
    partial void Onactive_idChanged();
    partial void Onactive_userChanging(string value);
    partial void Onactive_userChanged();
    #endregion
		
		public Tbl_giftcode()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int item_id
		{
			get
			{
				return this._item_id;
			}
			set
			{
				if ((this._item_id != value))
				{
					this.Onitem_idChanging(value);
					this.SendPropertyChanging();
					this._item_id = value;
					this.SendPropertyChanged("item_id");
					this.Onitem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gift_code", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string gift_code
		{
			get
			{
				return this._gift_code;
			}
			set
			{
				if ((this._gift_code != value))
				{
					this.Ongift_codeChanging(value);
					this.SendPropertyChanging();
					this._gift_code = value;
					this.SendPropertyChanged("gift_code");
					this.Ongift_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_code", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string item_code
		{
			get
			{
				return this._item_code;
			}
			set
			{
				if ((this._item_code != value))
				{
					this.Onitem_codeChanging(value);
					this.SendPropertyChanging();
					this._item_code = value;
					this.SendPropertyChanged("item_code");
					this.Onitem_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_group_user", DbType="VarChar(8000)")]
		public string group_user
		{
			get
			{
				return this._group_user;
			}
			set
			{
				if ((this._group_user != value))
				{
					this.Ongroup_userChanging(value);
					this.SendPropertyChanging();
					this._group_user = value;
					this.SendPropertyChanged("group_user");
					this.Ongroup_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active_id", DbType="Int")]
		public System.Nullable<int> active_id
		{
			get
			{
				return this._active_id;
			}
			set
			{
				if ((this._active_id != value))
				{
					this.Onactive_idChanging(value);
					this.SendPropertyChanging();
					this._active_id = value;
					this.SendPropertyChanged("active_id");
					this.Onactive_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active_user", DbType="VarChar(8000)")]
		public string active_user
		{
			get
			{
				return this._active_user;
			}
			set
			{
				if ((this._active_user != value))
				{
					this.Onactive_userChanging(value);
					this.SendPropertyChanging();
					this._active_user = value;
					this.SendPropertyChanged("active_user");
					this.Onactive_userChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Member_Password")]
	public partial class Tbl_Member_Password : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userid;
		
		private string _userpassword;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    partial void OnuserpasswordChanging(string value);
    partial void OnuserpasswordChanged();
    #endregion
		
		public Tbl_Member_Password()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userpassword", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string userpassword
		{
			get
			{
				return this._userpassword;
			}
			set
			{
				if ((this._userpassword != value))
				{
					this.OnuserpasswordChanging(value);
					this.SendPropertyChanging();
					this._userpassword = value;
					this.SendPropertyChanged("userpassword");
					this.OnuserpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[9d_event]")]
	public partial class _9d_event : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _event_id;
		
		private string _event_name;
		
		private string _event_link;
		
		private string _event_image;
		
		private string _event_title;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onevent_idChanging(int value);
    partial void Onevent_idChanged();
    partial void Onevent_nameChanging(string value);
    partial void Onevent_nameChanged();
    partial void Onevent_linkChanging(string value);
    partial void Onevent_linkChanged();
    partial void Onevent_imageChanging(string value);
    partial void Onevent_imageChanged();
    partial void Onevent_titleChanging(string value);
    partial void Onevent_titleChanged();
    #endregion
		
		public _9d_event()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int event_id
		{
			get
			{
				return this._event_id;
			}
			set
			{
				if ((this._event_id != value))
				{
					this.Onevent_idChanging(value);
					this.SendPropertyChanging();
					this._event_id = value;
					this.SendPropertyChanged("event_id");
					this.Onevent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string event_name
		{
			get
			{
				return this._event_name;
			}
			set
			{
				if ((this._event_name != value))
				{
					this.Onevent_nameChanging(value);
					this.SendPropertyChanging();
					this._event_name = value;
					this.SendPropertyChanged("event_name");
					this.Onevent_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_link", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string event_link
		{
			get
			{
				return this._event_link;
			}
			set
			{
				if ((this._event_link != value))
				{
					this.Onevent_linkChanging(value);
					this.SendPropertyChanging();
					this._event_link = value;
					this.SendPropertyChanged("event_link");
					this.Onevent_linkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_image", DbType="NVarChar(255)")]
		public string event_image
		{
			get
			{
				return this._event_image;
			}
			set
			{
				if ((this._event_image != value))
				{
					this.Onevent_imageChanging(value);
					this.SendPropertyChanging();
					this._event_image = value;
					this.SendPropertyChanged("event_image");
					this.Onevent_imageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_title", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string event_title
		{
			get
			{
				return this._event_title;
			}
			set
			{
				if ((this._event_title != value))
				{
					this.Onevent_titleChanging(value);
					this.SendPropertyChanging();
					this._event_title = value;
					this.SendPropertyChanged("event_title");
					this.Onevent_titleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[9d_users]")]
	public partial class _9d_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _user_name;
		
		private string _password;
		
		private string _email;
		
		private string _telephone;
		
		private string _address;
		
		private System.Nullable<int> _level;
		
		private System.Nullable<int> _totalpost;
		
		private int _balance;
		
		private bool _isActivate;
		
		private string _ActivateCode;
		
		private System.DateTime _created_at;
		
		private string _created_by;
		
		private System.Nullable<bool> _delete_flag;
		
		private System.Nullable<bool> _status;
		
		private string _message;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OntelephoneChanging(string value);
    partial void OntelephoneChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnlevelChanging(System.Nullable<int> value);
    partial void OnlevelChanged();
    partial void OntotalpostChanging(System.Nullable<int> value);
    partial void OntotalpostChanged();
    partial void OnbalanceChanging(int value);
    partial void OnbalanceChanged();
    partial void OnisActivateChanging(bool value);
    partial void OnisActivateChanged();
    partial void OnActivateCodeChanging(string value);
    partial void OnActivateCodeChanged();
    partial void Oncreated_atChanging(System.DateTime value);
    partial void Oncreated_atChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Ondelete_flagChanging(System.Nullable<bool> value);
    partial void Ondelete_flagChanged();
    partial void OnstatusChanging(System.Nullable<bool> value);
    partial void OnstatusChanged();
    partial void OnmessageChanging(string value);
    partial void OnmessageChanged();
    #endregion
		
		public _9d_user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this.OntelephoneChanging(value);
					this.SendPropertyChanging();
					this._telephone = value;
					this.SendPropertyChanged("telephone");
					this.OntelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[level]", Storage="_level", DbType="Int")]
		public System.Nullable<int> level
		{
			get
			{
				return this._level;
			}
			set
			{
				if ((this._level != value))
				{
					this.OnlevelChanging(value);
					this.SendPropertyChanging();
					this._level = value;
					this.SendPropertyChanged("level");
					this.OnlevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalpost", DbType="Int")]
		public System.Nullable<int> totalpost
		{
			get
			{
				return this._totalpost;
			}
			set
			{
				if ((this._totalpost != value))
				{
					this.OntotalpostChanging(value);
					this.SendPropertyChanging();
					this._totalpost = value;
					this.SendPropertyChanged("totalpost");
					this.OntotalpostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance", DbType="Int NOT NULL")]
		public int balance
		{
			get
			{
				return this._balance;
			}
			set
			{
				if ((this._balance != value))
				{
					this.OnbalanceChanging(value);
					this.SendPropertyChanging();
					this._balance = value;
					this.SendPropertyChanged("balance");
					this.OnbalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActivate", DbType="Bit NOT NULL")]
		public bool isActivate
		{
			get
			{
				return this._isActivate;
			}
			set
			{
				if ((this._isActivate != value))
				{
					this.OnisActivateChanging(value);
					this.SendPropertyChanging();
					this._isActivate = value;
					this.SendPropertyChanged("isActivate");
					this.OnisActivateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivateCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ActivateCode
		{
			get
			{
				return this._ActivateCode;
			}
			set
			{
				if ((this._ActivateCode != value))
				{
					this.OnActivateCodeChanging(value);
					this.SendPropertyChanging();
					this._ActivateCode = value;
					this.SendPropertyChanged("ActivateCode");
					this.OnActivateCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime NOT NULL")]
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_flag", DbType="Bit")]
		public System.Nullable<bool> delete_flag
		{
			get
			{
				return this._delete_flag;
			}
			set
			{
				if ((this._delete_flag != value))
				{
					this.Ondelete_flagChanging(value);
					this.SendPropertyChanging();
					this._delete_flag = value;
					this.SendPropertyChanged("delete_flag");
					this.Ondelete_flagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit")]
		public System.Nullable<bool> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message", DbType="NVarChar(999)")]
		public string message
		{
			get
			{
				return this._message;
			}
			set
			{
				if ((this._message != value))
				{
					this.OnmessageChanging(value);
					this.SendPropertyChanging();
					this._message = value;
					this.SendPropertyChanged("message");
					this.OnmessageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.User_History")]
	public partial class User_History : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _user_name;
		
		private System.Nullable<System.DateTime> _time_into;
		
		private string _car_info;
		
		private string _car_type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Ontime_intoChanging(System.Nullable<System.DateTime> value);
    partial void Ontime_intoChanged();
    partial void Oncar_infoChanging(string value);
    partial void Oncar_infoChanged();
    partial void Oncar_typeChanging(string value);
    partial void Oncar_typeChanged();
    #endregion
		
		public User_History()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_into", DbType="DateTime")]
		public System.Nullable<System.DateTime> time_into
		{
			get
			{
				return this._time_into;
			}
			set
			{
				if ((this._time_into != value))
				{
					this.Ontime_intoChanging(value);
					this.SendPropertyChanging();
					this._time_into = value;
					this.SendPropertyChanged("time_into");
					this.Ontime_intoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_info", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string car_info
		{
			get
			{
				return this._car_info;
			}
			set
			{
				if ((this._car_info != value))
				{
					this.Oncar_infoChanging(value);
					this.SendPropertyChanging();
					this._car_info = value;
					this.SendPropertyChanged("car_info");
					this.Oncar_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_type", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string car_type
		{
			get
			{
				return this._car_type;
			}
			set
			{
				if ((this._car_type != value))
				{
					this.Oncar_typeChanging(value);
					this.SendPropertyChanging();
					this._car_type = value;
					this.SendPropertyChanged("car_type");
					this.Oncar_typeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[9d_KTCItems]")]
	public partial class _9d_KTCItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _itemid;
		
		private string _itemname;
		
		private string _itemimages;
		
		private int _itemprice;
		
		private string _itemdescription;
		
		private System.DateTime _created_at;
		
		private string _created_by;
		
		private System.DateTime _updated_at;
		
		private string _updated_by;
		
		private bool _delete_flag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnitemidChanging(string value);
    partial void OnitemidChanged();
    partial void OnitemnameChanging(string value);
    partial void OnitemnameChanged();
    partial void OnitemimagesChanging(string value);
    partial void OnitemimagesChanged();
    partial void OnitempriceChanging(int value);
    partial void OnitempriceChanged();
    partial void OnitemdescriptionChanging(string value);
    partial void OnitemdescriptionChanged();
    partial void Oncreated_atChanging(System.DateTime value);
    partial void Oncreated_atChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Onupdated_atChanging(System.DateTime value);
    partial void Onupdated_atChanged();
    partial void Onupdated_byChanging(string value);
    partial void Onupdated_byChanged();
    partial void Ondelete_flagChanging(bool value);
    partial void Ondelete_flagChanged();
    #endregion
		
		public _9d_KTCItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string itemid
		{
			get
			{
				return this._itemid;
			}
			set
			{
				if ((this._itemid != value))
				{
					this.OnitemidChanging(value);
					this.SendPropertyChanging();
					this._itemid = value;
					this.SendPropertyChanged("itemid");
					this.OnitemidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string itemname
		{
			get
			{
				return this._itemname;
			}
			set
			{
				if ((this._itemname != value))
				{
					this.OnitemnameChanging(value);
					this.SendPropertyChanging();
					this._itemname = value;
					this.SendPropertyChanged("itemname");
					this.OnitemnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemimages", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string itemimages
		{
			get
			{
				return this._itemimages;
			}
			set
			{
				if ((this._itemimages != value))
				{
					this.OnitemimagesChanging(value);
					this.SendPropertyChanging();
					this._itemimages = value;
					this.SendPropertyChanged("itemimages");
					this.OnitemimagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemprice", DbType="Int NOT NULL")]
		public int itemprice
		{
			get
			{
				return this._itemprice;
			}
			set
			{
				if ((this._itemprice != value))
				{
					this.OnitempriceChanging(value);
					this.SendPropertyChanging();
					this._itemprice = value;
					this.SendPropertyChanged("itemprice");
					this.OnitempriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemdescription", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string itemdescription
		{
			get
			{
				return this._itemdescription;
			}
			set
			{
				if ((this._itemdescription != value))
				{
					this.OnitemdescriptionChanging(value);
					this.SendPropertyChanging();
					this._itemdescription = value;
					this.SendPropertyChanged("itemdescription");
					this.OnitemdescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime NOT NULL")]
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime NOT NULL")]
		public System.DateTime updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_by", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string updated_by
		{
			get
			{
				return this._updated_by;
			}
			set
			{
				if ((this._updated_by != value))
				{
					this.Onupdated_byChanging(value);
					this.SendPropertyChanging();
					this._updated_by = value;
					this.SendPropertyChanged("updated_by");
					this.Onupdated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_flag", DbType="Bit NOT NULL")]
		public bool delete_flag
		{
			get
			{
				return this._delete_flag;
			}
			set
			{
				if ((this._delete_flag != value))
				{
					this.Ondelete_flagChanging(value);
					this.SendPropertyChanging();
					this._delete_flag = value;
					this.SendPropertyChanged("delete_flag");
					this.Ondelete_flagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[9d_news]")]
	public partial class _9d_new : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _news_id;
		
		private string _news_title;
		
		private string _news_ascii;
		
		private string _news_images;
		
		private int _type;
		
		private string _news_descriptions;
		
		private string _news_content;
		
		private System.DateTime _created_at;
		
		private string _created_by;
		
		private System.Nullable<bool> _delete_flag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnews_idChanging(int value);
    partial void Onnews_idChanged();
    partial void Onnews_titleChanging(string value);
    partial void Onnews_titleChanged();
    partial void Onnews_asciiChanging(string value);
    partial void Onnews_asciiChanged();
    partial void Onnews_imagesChanging(string value);
    partial void Onnews_imagesChanged();
    partial void OntypeChanging(int value);
    partial void OntypeChanged();
    partial void Onnews_descriptionsChanging(string value);
    partial void Onnews_descriptionsChanged();
    partial void Onnews_contentChanging(string value);
    partial void Onnews_contentChanged();
    partial void Oncreated_atChanging(System.DateTime value);
    partial void Oncreated_atChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Ondelete_flagChanging(System.Nullable<bool> value);
    partial void Ondelete_flagChanged();
    #endregion
		
		public _9d_new()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int news_id
		{
			get
			{
				return this._news_id;
			}
			set
			{
				if ((this._news_id != value))
				{
					this.Onnews_idChanging(value);
					this.SendPropertyChanging();
					this._news_id = value;
					this.SendPropertyChanged("news_id");
					this.Onnews_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_title", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string news_title
		{
			get
			{
				return this._news_title;
			}
			set
			{
				if ((this._news_title != value))
				{
					this.Onnews_titleChanging(value);
					this.SendPropertyChanging();
					this._news_title = value;
					this.SendPropertyChanged("news_title");
					this.Onnews_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_ascii", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string news_ascii
		{
			get
			{
				return this._news_ascii;
			}
			set
			{
				if ((this._news_ascii != value))
				{
					this.Onnews_asciiChanging(value);
					this.SendPropertyChanging();
					this._news_ascii = value;
					this.SendPropertyChanged("news_ascii");
					this.Onnews_asciiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_images", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string news_images
		{
			get
			{
				return this._news_images;
			}
			set
			{
				if ((this._news_images != value))
				{
					this.Onnews_imagesChanging(value);
					this.SendPropertyChanging();
					this._news_images = value;
					this.SendPropertyChanged("news_images");
					this.Onnews_imagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int NOT NULL")]
		public int type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_descriptions", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string news_descriptions
		{
			get
			{
				return this._news_descriptions;
			}
			set
			{
				if ((this._news_descriptions != value))
				{
					this.Onnews_descriptionsChanging(value);
					this.SendPropertyChanging();
					this._news_descriptions = value;
					this.SendPropertyChanged("news_descriptions");
					this.Onnews_descriptionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_content", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string news_content
		{
			get
			{
				return this._news_content;
			}
			set
			{
				if ((this._news_content != value))
				{
					this.Onnews_contentChanging(value);
					this.SendPropertyChanging();
					this._news_content = value;
					this.SendPropertyChanged("news_content");
					this.Onnews_contentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime NOT NULL")]
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_flag", DbType="Bit")]
		public System.Nullable<bool> delete_flag
		{
			get
			{
				return this._delete_flag;
			}
			set
			{
				if ((this._delete_flag != value))
				{
					this.Ondelete_flagChanging(value);
					this.SendPropertyChanging();
					this._delete_flag = value;
					this.SendPropertyChanged("delete_flag");
					this.Ondelete_flagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[9d_ads]")]
	public partial class _9d_ad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ads_id;
		
		private int _ads_type;
		
		private string _ads_name;
		
		private string _ads_link;
		
		private string _ads_image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onads_idChanging(int value);
    partial void Onads_idChanged();
    partial void Onads_typeChanging(int value);
    partial void Onads_typeChanged();
    partial void Onads_nameChanging(string value);
    partial void Onads_nameChanged();
    partial void Onads_linkChanging(string value);
    partial void Onads_linkChanged();
    partial void Onads_imageChanging(string value);
    partial void Onads_imageChanged();
    #endregion
		
		public _9d_ad()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ads_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ads_id
		{
			get
			{
				return this._ads_id;
			}
			set
			{
				if ((this._ads_id != value))
				{
					this.Onads_idChanging(value);
					this.SendPropertyChanging();
					this._ads_id = value;
					this.SendPropertyChanged("ads_id");
					this.Onads_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ads_type", DbType="Int NOT NULL")]
		public int ads_type
		{
			get
			{
				return this._ads_type;
			}
			set
			{
				if ((this._ads_type != value))
				{
					this.Onads_typeChanging(value);
					this.SendPropertyChanging();
					this._ads_type = value;
					this.SendPropertyChanged("ads_type");
					this.Onads_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ads_name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ads_name
		{
			get
			{
				return this._ads_name;
			}
			set
			{
				if ((this._ads_name != value))
				{
					this.Onads_nameChanging(value);
					this.SendPropertyChanging();
					this._ads_name = value;
					this.SendPropertyChanged("ads_name");
					this.Onads_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ads_link", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ads_link
		{
			get
			{
				return this._ads_link;
			}
			set
			{
				if ((this._ads_link != value))
				{
					this.Onads_linkChanging(value);
					this.SendPropertyChanging();
					this._ads_link = value;
					this.SendPropertyChanged("ads_link");
					this.Onads_linkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ads_image", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ads_image
		{
			get
			{
				return this._ads_image;
			}
			set
			{
				if ((this._ads_image != value))
				{
					this.Onads_imageChanging(value);
					this.SendPropertyChanging();
					this._ads_image = value;
					this.SendPropertyChanged("ads_image");
					this.Onads_imageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[9d_percen]")]
	public partial class _9d_percen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _percen_id;
		
		private int _percen;
		
		private System.Nullable<bool> _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpercen_idChanging(int value);
    partial void Onpercen_idChanged();
    partial void OnpercenChanging(int value);
    partial void OnpercenChanged();
    partial void OnstatusChanging(System.Nullable<bool> value);
    partial void OnstatusChanged();
    #endregion
		
		public _9d_percen()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_percen_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int percen_id
		{
			get
			{
				return this._percen_id;
			}
			set
			{
				if ((this._percen_id != value))
				{
					this.Onpercen_idChanging(value);
					this.SendPropertyChanging();
					this._percen_id = value;
					this.SendPropertyChanged("percen_id");
					this.Onpercen_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_percen", DbType="Int NOT NULL")]
		public int percen
		{
			get
			{
				return this._percen;
			}
			set
			{
				if ((this._percen != value))
				{
					this.OnpercenChanging(value);
					this.SendPropertyChanging();
					this._percen = value;
					this.SendPropertyChanged("percen");
					this.OnpercenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit")]
		public System.Nullable<bool> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
