#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tempofme.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ND_GAME_0")]
	public partial class DataNDGameDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataNDGameDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ND_GAME_0ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataNDGameDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataNDGameDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataNDGameDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataNDGameDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VIEW_RANK_INFO> VIEW_RANK_INFOs
		{
			get
			{
				return this.GetTable<VIEW_RANK_INFO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_RANK_INFO")]
	public partial class VIEW_RANK_INFO
	{
		
		private int _unique_id;
		
		private string _chr_name;
		
		private short _inner_level;
		
		private long _jin;
		
		private short _party;
		
		private short _class;
		
		private int _honor;
		
		private System.Nullable<int> _hiding;
		
		public VIEW_RANK_INFO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unique_id", DbType="Int NOT NULL")]
		public int unique_id
		{
			get
			{
				return this._unique_id;
			}
			set
			{
				if ((this._unique_id != value))
				{
					this._unique_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chr_name", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string chr_name
		{
			get
			{
				return this._chr_name;
			}
			set
			{
				if ((this._chr_name != value))
				{
					this._chr_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inner_level", DbType="SmallInt NOT NULL")]
		public short inner_level
		{
			get
			{
				return this._inner_level;
			}
			set
			{
				if ((this._inner_level != value))
				{
					this._inner_level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jin", DbType="BigInt NOT NULL")]
		public long jin
		{
			get
			{
				return this._jin;
			}
			set
			{
				if ((this._jin != value))
				{
					this._jin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_party", DbType="SmallInt NOT NULL")]
		public short party
		{
			get
			{
				return this._party;
			}
			set
			{
				if ((this._party != value))
				{
					this._party = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="class", Storage="_class", DbType="SmallInt NOT NULL")]
		public short @class
		{
			get
			{
				return this._class;
			}
			set
			{
				if ((this._class != value))
				{
					this._class = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_honor", DbType="Int NOT NULL")]
		public int honor
		{
			get
			{
				return this._honor;
			}
			set
			{
				if ((this._honor != value))
				{
					this._honor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hiding", DbType="Int")]
		public System.Nullable<int> hiding
		{
			get
			{
				return this._hiding;
			}
			set
			{
				if ((this._hiding != value))
				{
					this._hiding = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
